# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: 'Default'  # This is the name of your agent pool, 'Default' is common, but you can use a custom name if you've created one
  demands:
  - maven
  - Agent.Version -gtVersion 2.163.1
#    - agent.name -equals 'FEMI'  # Replace 'FEMI' with the name of your self-hosted agent if different


steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKUserInputPath'  # Specify JDK path using JDKUserInputPath
    jdkUserInputPath: 'C:\Program Files\Java\jdk-23'  # Specify the JDK path here
    jdkVersionOption: '23'  # Specify JDK version 23 for the build
    jdkArchitectureOption: 'x64'
    mavenVersionOption: 'Default'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/webapp/target'
    Contents: '**/*'  
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'