trigger:
  - main

pool:
  name: 'Default'
  demands:
    - agent.name -equals FEMI
    - maven
    - Agent.Version -gtVersion 2.163.1

stages:
  # Build Stage
  - stage: Build
    displayName: Build Application
    jobs:
      - job: BuildJob
        displayName: Build Job
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'webapp/pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKUserInputPath'
              jdkUserInputPath: 'C:\Program Files\Java\jdk-23'
              jdkVersionOption: '23'
              jdkArchitectureOption: 'x64'
              mavenVersionOption: 'Default'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'package'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/webapp/target'
              Contents: '**/*.war'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'warfile'
              publishLocation: 'Container'

  # Deploy Stage
  - stage: Deploy
    displayName: Deploy Application
    dependsOn: Build
    jobs:
      - job: DeployJob
        displayName: Deploy to Tomcat
        steps:
          # Download artifact
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'warfile'
              targetPath: 'C:\vsts-agent-win-x64-4.248.0\_work\1\warfile'

          # Verify the downloaded artifact
          - script: |
              echo "Listing contents of downloaded artifact folder..."
              dir "C:\vsts-agent-win-x64-4.248.0\_work\1\warfile"
            displayName: 'Verify Artifact Contents'
   
          # Copy WAR to Tomcat
          - script: |
              echo "Copying WAR file to Tomcat webapps folder..."
              for /R "C:\vsts-agent-win-x64-4.248.0\_work\1\warfile" %%f in (*.war) do (
                  echo "Copying %%f to C:\Users\femip\Downloads\apache-tomcat-10.1.33-windows-x64\apache-tomcat-10.1.33\webapps"
                  copy "%%f" "C:\Users\femip\Downloads\apache-tomcat-10.1.33-windows-x64\apache-tomcat-10.1.33\webapps"
              )
            displayName: 'Copy WAR to Tomcat'

          # Restart Tomcat manually (shutdown and startup)
          - script: |
              echo "Stopping Tomcat server..."
              C:\Users\femip\Downloads\apache-tomcat-10.1.33-windows-x64\apache-tomcat-10.1.33\bin\shutdown.bat
              echo "Starting Tomcat server..."
              C:\Users\femip\Downloads\apache-tomcat-10.1.33-windows-x64\apache-tomcat-10.1.33\bin\startup.bat
            displayName: 'Restart Tomcat Server Manually'
#14:12update