# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: 'Default'  # This is the name of your agent pool, 'Default' is common, but you can use a custom name if you've created one
  demands:
  - maven
  - Agent.Version -gtVersion 2.163.1
#    - agent.name -equals 'FEMI'  # Replace 'FEMI' with the name of your self-hosted agent if different


steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    jdkVersionOption: '21'  # Specify JDK 21 for the build
    javaHomeOption: 'JDK21'  # Ensure this is also JDK 21
    jdkArchitectureOption: 'x64'  # Architecture of the JDK
    mavenVersionOption: 'Default'  # Use the default Maven version installed
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
